name: Test TeXLive Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: fredqi/tl-action@xelatex
        with:
          tex_files: |
            test/test-xe.tex
      - name: Check pdf files
        run: |
          file test/test-xe.pdf | grep -q 'PDF'
