name: Test TeXLive Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: repaction/texlive@main
        with:
          tex_files: |
            test/test.tex
            test/math.tex
      - name: Check pdf files
        run: |
          file test/test.pdf | grep -q 'PDF'
          file test/math.pdf | grep -q ' PDF '
